_id: findBgpConfigByProject1
type: Request
parentId: fld_wrk_4927d0e0404d4fc9b977fd3a6ec817635e543b17
modified: 1617357789993
created: 1617357789993
url: "{{ base_url }}/projects/{{ id }}/bgp-config"
name: Retrieve a bgp config
description: Returns a bgp config
method: GET
body: {}
parameters:
  - name: include
    disabled: true
    value: string
  - name: exclude
    disabled: true
    value: string
headers: []
authentication: {}
metaSortKey: -1617357789993
isPrivate: false
settingStoreCookies: true
settingSendCookies: true
settingDisableRenderRequestBody: false
settingEncodeUrl: true
settingRebuildPath: true
settingFollowRedirects: global
