_id: findCurrentUserVpnConfig
type: Request
parentId: fld_wrk_4927d0e0404d4fc9b977fd3a6ec8176333b7378d
modified: 1617357789106
created: 1617357789106
url: "{{ base_url }}/user/vpn"
name: Retrieve the client vpn config for current user
description: Returns the client vpn config for the currently logged-in user.
method: GET
body: {}
parameters:
  - name: code
    disabled: false
    value: string
headers: []
authentication: {}
metaSortKey: -1617357789107
isPrivate: false
settingStoreCookies: true
settingSendCookies: true
settingDisableRenderRequestBody: false
settingEncodeUrl: true
settingRebuildPath: true
settingFollowRedirects: global
