_id: requestBgpConfig1
type: Request
parentId: fld_wrk_4927d0e0404d4fc9b977fd3a6ec817635e543b17
modified: 1617357789999
created: 1617357789999
url: "{{ base_url }}/projects/{{ id }}/bgp-configs"
name: Requesting bgp config
description: Requests to enable bgp configuration for a project.
method: POST
body:
  mimeType: application/json
  text: |-
    {
      "deployment_type": "string",
      "asn": 0,
      "md5": "string",
      "use_case": "string"
    }
parameters: []
headers:
  - name: Content-Type
    disabled: false
    value: application/json
authentication: {}
metaSortKey: -1617357789999
isPrivate: false
settingStoreCookies: true
settingSendCookies: true
settingDisableRenderRequestBody: false
settingEncodeUrl: true
settingRebuildPath: true
settingFollowRedirects: global
